apiVersion: v1
kind: Service
metadata:
  name: my-node-webserver-service
  labels:
    run: my-node-webserver-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocal: TCP
    targetPort: 3000
  selector:
    app: node
